### ISSUE TITLE
Unable to set up working Cluster Issuer

### ISSUE THREAD

**Issue by MrKickkiller** [aureq/cert-manager-webhook-ovh#1]
Application is able to install to my cluster, seems to be running fine, however. I keep getting `HTTP Error 400: "Invalid signature"` in the output of cert manager itself.

Node time is accurate to about a second

Cluster Issuer
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: <email>
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    # Enable the DNS-01 challenge provider
    solvers:
      - dns01:
          webhook:
            groupName: "<some group name>"
            solverName: ovh
            config:
              endpoint: ovh-eu
              applicationKeyRef:
                key: applicationKey
                name: ovh-dns
              applicationSecretRef:
                key: applicationSecret
                name: ovh-dns
              consumerKey:
                key: consumerKey
                name: ovh-dns
```

```
apiVersion: v1
kind: Secret
metadata:
  namespace: cert-manager
  name: ovh-dns
  annotations:
    kubernetes.io/service-account.name: default
type: Opaque
data:
  applicationKey: <>
  applicationSecret: <>
  consumerKey: <>

```
Secret and its content has been validated by using postman and some pre-request scripting to perform a `GET /domain/zone/<domain>/status` myself, I get a 200 back, no problem.

After browsing trough your code, I don't see where it is going wrong. You seem to be handling errors well when fetching the values from the secrets. Could you perhaps add in a trace/verbose mode where more log output can be seen?

~Upon further inspection in your code, I never spot the "Validation passed" log in the output of the webhook. Meaning `allowAmbientCredentials` is probably true. Where does this value come from?~
Nvm, this is correct in my use case. It means it will load from the secrets. And since I don't see any errors in your compoent & the call actually went out to OVH, I gotta assume that went ok.
