### ISSUE TITLE
Error presenting challenge: /domain/zone/com/status - HTTP Error 404

### ISSUE THREAD

**Issue by Yethal** [aureq/cert-manager-webhook-ovh#11]
My Challenges fail with following error:
```Error presenting challenge: OVH API call failed: GET /domain/zone/com/status - HTTP Error 404: "This service does not exist"```

It seems that the domain name was improperly parsed resulting in `com` being used instead of the actual domain name despite correct A records existing for the domain

**Comment by aureq** [comment]
Hey @Yethal 

I need more information there...

What's your Helm chart configuration? What's the domain name you're using?
Which version of the Helm chart you've deployed? And which version of Cert Manager are you using?
Likewise, what version of k8s are you using? and which platform?

Is it a fresh deployment, or an upgrade? And if so, what was the previous version?

**Comment by Yethal** [comment]
* cert-manager 1.10.1 deployed via helm with installCRDs set to true
* cert-manager-webhook-ovh 0.4.1 deployed via helm with single Cluster issuer and api keys provided directly in the values
* k3s version  v1.26.0+k3s1 on Ubuntu 22.04
* Fresh deployment

**Comment by aureq** [comment]
What's your `values.yaml`? (make sure to redact any sensitive credentials).

**Comment by Yethal** [comment]
```
groupName: "acme.{{ domain }}"
issuers:
   - name: letsencrypt
     create: true
     kind: ClusterIssuer
     cnameStrategy: None
     acmeServerUrl: https://acme-v02.api.letsencrypt.org/directory
     email: "{{ email }}"
     ovhEndpointName: ovh-eu
     ovhAuthentication:
       applicationKey: "{{ application_key }}"
       applicationSecret: "{{ application_secret }}"
       consumerKey: "{{ consumer_key }}"
```

**Comment by aureq** [comment]
From what I see, there's nothing unusual. You should review the resource that triggers the certificate request. I would also recommend reading cert manager own logs as it may offer some clue as well.

**Comment by Yethal** [comment]
Not sure whether this is relevant but the service I'm trying to generate the cert for is exposed on domain root, not on a subdomain

**Comment by aureq** [comment]
How are you requesting the certificate issuance? Dp you mind sharing the YAML?

**Comment by Yethal** [comment]
```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: nginx
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: "poteznedinozaury.com"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
  tls:
    - hosts:
      - "poteznedinozaury.com"
      secretName: poteznedinozaury-com-tls
```
I moved the service to a subdomain but got the same bug (com as domain name)
