### ISSUE TITLE
Error presenting challenge: OVH API call failed: GET /domain/zone/subdomain.xxx.xxx/status - HTTP Error 404: "This service does not exist"

### ISSUE THREAD

**Issue by AldoArtellium** [aureq/cert-manager-webhook-ovh#16]
Hello, 
I have a problem when issuing certificate to OVH getting the following error:
`Error presenting challenge: OVH API call failed: GET /domain/zone/subdomain.xxx.xxx/status - HTTP Error 404: "This service does not exist"`

I have been using baarde's project and getting this error, I wanted to try out this repo but the same error occur.
I tried to reset our k3s cluster, nothing changes.

The problem is that the OVH API call is trying to get the domain but with the subdomain which is not a defined zone. 
The weird thing is that in the prod environment it works well but in our office we get this.
I don't see anything wrong that differs from our prod besides versions.

APP VERSION in our prod wich is working:
**k8s rev: v1.23.14+k3s1
cert-manager : v1.9.1
baarde's project cert-manager-webhook-ovh : 0.3.0**

APP VERSION in our office:
**k8s rev: v1.25.5+k3s2
cert-manager : v1.11.0
cert-manager-webhook-ovh : v0.4.1**

values.yml:
```
groupName: acme.xxx.xxx

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

issuers:
  - name: letsencrypt
    create: true
    kind: ClusterIssuer
    namespace: cert-manager
    cnameStrategy: None
    acmeServerUrl: https://acme-v02.api.letsencrypt.org/directory
    email: acme@xxx.xxx
    ovhEndpointName: ovh-eu
    ovhAuthentication:
      applicationKey: 'xx'
      applicationSecret: 'xx'
      consumerKey: 'xx'
```

certificate.yml:
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xxx-xxx
spec:
  commonName: "*.subdomain.xxx.xxx"
  dnsNames:
  - "*.subdomain.xxx.xxx"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: xxx-xxx-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ""
```

Do you have ideas ? Ive been stuck on this error for week

Thanks
