### ISSUE TITLE
User cannot create resource "ovh" in API group at the cluster scope

### ISSUE THREAD

**Issue by Alissia01** [aureq/cert-manager-webhook-ovh#19]
Hi,

I have a problem with the challenge not being done.
Event in my challenge ressource :

`Warning  PresentError  10m (x8 over 20m)  cert-manager-challenges  Error presenting challenge: ovh.acme.alissia-port.fr is forbidden: User "system:serviceaccount:cert-manager:alissia-cert-manager" cannot create resource "ovh" in API group "acme.alissia-port.fr" at the cluster scope`

My setup is a chart with cert-manager as a subchart.

Any idea?
Thanks!

**Comment by aureq** [comment]
No I don't actually.

I would recommend the following:

- Deploy the chart as such, not as a subchart (I never tested subchart deployments)
- Check the service account permissions, looks like it doesn't have Cluster permissions.
- Part of the Chart deployment, you should ensure you have at least one `ClusterIssuer` with `create: true`

**Comment by Alissia01** [comment]
Hi,

Thank you!

1.  Same problem
2. How do you do that? This is a concept of Kubernetes that I'm not familiar with that
3. Yes, it's good. `ClusterIssuer` are well created in the default namespace

**Comment by aureq** [comment]
I was reading again your error message, and I have spotted the issue. When you deployed Cert Manager, it create a `serviceAccount`. The `values.yaml` looks like this. Since it's the default value, I'm assuming a `serviceAccount` named `cert-manager` exists.

```yaml
serviceAccount:
  # Specifies whether a service account should be created
  create: true
```

However, your error message shows `system:serviceaccount:cert-manager:alissia-cert-manager`. Correct namespace, but incorrect service account.

So, what in your `values.yaml` for the OVH webhook? Below is the default value and this is likely what you should be using.

```yaml
certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager
```

**Comment by aureq** [comment]
This is the same issue as https://github.com/aureq/cert-manager-webhook-ovh/issues/17

**Comment by Alissia01** [comment]
Hello!

Thank you, this seems to have unblocked the situation!
However, I now get the error:

 `Warning  PresentError  53s (x7 over 5m58s)  cert-manager-challenges  Error presenting challenge: secrets "ovh-credentials" is forbidden: User "system:serviceaccount:default:alissia-cert-manager-webhook-ovh" cannot get resource "secrets" in API group "" in the namespace "cert-manager"`

The command `kubectl get secret -n cert-manager` get:

```
> kubectl get secret -n cert-manager
NAME                              TYPE     DATA   AGE
alissia-cert-manager-webhook-ca     Opaque   3      29h
letsencrypt-prod-account-key      Opaque   1      29h
letsencrypt-staging-account-key   Opaque   1      29h
ovh-credentials                   Opaque   3      4m31s
```

It looks like the cert-manager-webhook-ovh service does not have permission to retrieve the secret from the other namespace

**Comment by aureq** [comment]
I'm assuming you're using  a `secretRef` instead of letting the Chart creating the secret for you.

2 options:

1. Place your OVH credentials in `values.yaml` and let the Chart do the work
2. Update the role `cert-manager-webhook-ovh:secret-reader` to let it access your `ovh-credentials` secret. You'll have to read this [source code](cert-manager-webhook-ovh:secret-reader).

Mine looks like this.

```yaml
...
rules:
- apiGroups:
  - ""
  resourceNames:
  - letsencrypt-prod-ovh-credentials
  - letsencrypt-staging-ovh-credentials
  resources:
  - secrets
  verbs:
  - get
  - watch
```

**Comment by Alissia01** [comment]
1. I push my values.yaml file to a git repository, so I can't do that

2. Mine looks like this 👍 

```yaml
rules:
- apiGroups:
  - ""
  resourceNames:
  - ovh-credentials
  resources:
  - secrets
  verbs:
  - get
  - watch
```

Isn't the problem due to the fact that the resource is of type `Role` and not `ClusterRole`?

The role is in the `default` namespace, while the credentials are in `cert-manager`

**Comment by aureq** [comment]
Yes, sounds like it.

**Comment by Alissia01** [comment]
In this case, it may be interesting to have the possibility to define it in the values.yaml (or to change the service namespace)

**Comment by aureq** [comment]
Yes, do you mind sending a pull-request and I'll have a look at it.

**Comment by Alissia01** [comment]
Good, thank you!

**Comment by aureq** [comment]
Could you share your `values.yaml` please?

**Comment by Alissia01** [comment]
My `values.yaml` :

```
cert-manager-webhook-ovh:
  groupName: acme.alissia-port.fr
  certManager:
    namespace: cert-manager
    serviceAccountName: alissia-cert-manager
  issuers:
    - name: letsencrypt-prod
      create: true
      kind: ClusterIssuer
      namespace: cert-manager
      cnameStrategy: None
      acmeServerUrl: https://acme-v02.api.letsencrypt.org/directory
      email: "myEmail"
      ovhEndpointName: ovh-eu
      ovhAuthenticationRef:
        applicationKeyRef:
          name: ovh-credentials
          key: applicationKey
        applicationSecretRef:
          name: ovh-credentials
          key: applicationSecret
        consumerKeyRef:
          name: ovh-credentials
          key: consumerKey
    - name: letsencrypt-staging
      create: true
      kind: ClusterIssuer
      namespace: cert-manager
      cnameStrategy: None
      acmeServerUrl: https://acme-staging-v02.api.letsencrypt.org/directory
      email: "myEmail"
      ovhEndpointName: ovh-eu
      ovhAuthenticationRef:
        applicationKeyRef:
          name: ovh-credentials
          key: applicationKey
        applicationSecretRef:
          name: ovh-credentials
          key: applicationSecret
        consumerKeyRef:
          name: ovh-credentials
          key: consumerKey
```
