### ISSUE TITLE
Pre-level subdomain status is being checked when requesting a certificate for a subdomain

### ISSUE THREAD

**Issue by poponealex** [aureq/cert-manager-webhook-ovh#23]
### What happened?

I'm trying to generate a certificate for a wildcard subdomain `*.sub2.sub1.sld.tld` and the challenge fails with: `Error presenting challenge: OVH API call failed: GET /domain/zone/sub1.sld.tld/status - HTTP Error 404: "This service does not exist"`.

Indeed, `sub1.sld.tld` is not a correct DNS entry in our server. Although, `*.sub2.sub1.sld.tld` is a correct DNS entry and correctly answers to a dig request.

### Expected Behavior

When requesting a certficate for a subdomain such as `*.sub2.sub1.sld.tld` being a valid DNS entry and `sub1.sld.tld` not being a valid DNS entry, the challenge shouldn't fail. 

The status of `sub1.sld.tld` is not supposed to be checked since it is not the DNS entry for which we're trying to request a certificate. The status of `*.sub2.sub1.sld.tld` should be enough. If I'm mistaken, please let me know why and how I should fix this issue in my DNS configuration.

### Steps to reproduce

1. On your OVH account, create a DNS entry for `*.sub2.sub1.sld.tld` and make sure that there aren't any entries for `sub1.sld.tld` or `*.sld.tld` 
2. Create a certificate with the following configuration 
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: <CertificateName>
  namespace: cert-manager
spec:
  issuerRef:
    name: <ClusterIssuerName>
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - '*.sub2.sub1.sld.tld'
  isCA: false
  secretName: <TLSSecretName>
```
3. Look at the challenge's status

### Versions in use

- cert-manager-operator.v1.10.2 
- Kubernetes Version: v1.25.8+37a9a08
- OpenShift Version: 4.11.20
- Latest version of the chart installed via helm

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
