### ISSUE TITLE
Invalid header from OVH api

### ISSUE THREAD

**Issue by ArturZurawski** [aureq/cert-manager-webhook-ovh#7]
Hello, I migrated from https://github.com/baarde/cert-manager-webhook-ovh and this is first time when I'm trying to generate certs from this project. Previous one was working but I had to [disclose consumerKey](https://github.com/baarde/cert-manager-webhook-ovh/issues/21). After migrating I modified issuer:
```
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
#    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'mymail'
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        webhook:
          groupName: 'xx-xx'
          solverName: ovh
          config:
            endpoint: ovh-eu
            applicationKeyRef:
              key: applicationKey
              name: xx-xx-ovh-credentials
            applicationSecretRef:
              key: applicationSecret
              name: xx-xx-ovh-credentials
            consumerKeyRef:
              key: consumerKey
              name: xx-xx-ovh-credentials
```

values.yaml has:

```
cert-manager-webhook-ovh:
  certManager:
    namespace: cert-manager
    serviceAccountName: cert-manager
  image:
    repository: ghcr.io/aureq/cert-manager-webhook-ovh
    tag: v0.4.0
  groupName: xx-xx
  issuers:
  - name: letsencrypt
    create: false
```

and I'm getting weird error from cert manager pod:

```
I1121 15:27:06.179531       1 dns.go:88] cert-manager/challenges/Present "msg"="presenting DNS01 challenge for domain" "dnsName"="xx.xx" "domain"="xx.xx" "resource_kind"="Challenge" "resource_name"="xx-xx-jtgfx-3844061293-1738404956" "resource_namespace"="cert-manager" "resource_version"="v1" "type"="DNS-01"
E1121 15:27:06.458270       1 controller.go:167] cert-manager/challenges "msg"="re-queuing item due to error processing" "error"="OVH API call failed: GET /domain/zone/xx.xx/status - Get \"https://eu.api.ovh.com/1.0/domain/zone/xx.xx/status\": net/http: invalid header field value \"\\xef\\x9e\\xfc\\xe3M\\xfc\\xeb\\x8d5\\xf7M\\xb6ߎ5\\xe5\\xcd\\x1eӧ\\x9b\\xd3m\\xfd\" for key X -Ovh-Consumer" "key"="cert-manager/xx-xx-jtgfx-3844061293-1738404956"
```

Do you have any advice? Thanks in advance!

**Comment by ArturZurawski** [comment]
Yeah, rolled back config, chart and image to:
```
  image:
    repository: baarde/cert-manager-webhook-ovh
    tag: 0.3.0
```

And things are working.

Either I'm missing something in config (not sure what, `applicationKeyRef`  `applicationSecretRef` `consumerKeyRef` point to the right secrets) or something might be wrong with this container.

**Comment by ArturZurawski** [comment]
Hi. Yes this is whay I did initially. I rolled back to Baardes as I couldn't get cert using your fork. Error above.

**Comment by aureq** [comment]
@ArturZurawski A few things...

1 - You're using an `Issuer` instead of a `ClusterIssuer` (in case this is unintentional). You will only be able to issue certs inside the `cert-manager` namespace. See [docs](https://aureq.github.io/cert-manager-webhook-ovh/#issuer-vs-clusterissuer).
2 - You should check the content of this secret `xx-xx-ovh-credentials` and it should be the correct namespace.
3 - The secret `xx-xx-ovh-credentials` should have the following 3 keys `applicationKey`, `applicationSecret` and `consumerKey`, especially when using `ovhAuthenticationRef` in your `values.yaml`. See [docs](https://aureq.github.io/cert-manager-webhook-ovh/#secret-vs-secret-references).

**Comment by ArturZurawski** [comment]
@aureq thank you for your help.
Ad 1 - I'm fine with that. Also, that wouldn't result in error from OVH api while generating cert, right?
Ad 2 - secret is created in a proper namespace. It was already when I was using baarde's. I just added `consumerKey` and `applicationSecret`
```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: xx-xx-ovh-credentials
  namespace: cert-manager
spec:
  encryptedData:
    applicationKey: xxx
    applicationSecret: xxx
    consumerKey: xxx
  template:
    metadata:
      creationTimestamp: null
      name: xx-xx-ovh-credentials
      namespace: cert-manager
```
Ad 3 - as shoved above. All three there.
